language: node_js
node_js:
  - '8.9.4'
env:
  - CI=true
before_script:
  - yarn install
script:
  - npm test -- --coverage
  - npm run coveralls
  # - ./node_modules/jshint/bin/jshint lib/*.js
  # - ./node_modules/jshint/bin/jshint test/*.js
after_failure:
  - ls -1 log
  - cat log/*
